refresh_rate: 172800 seconds

appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%d/%m/%Y %H:%M:%S%.3f)} {h({l})} - {m}\n"

  requests:
    kind: file
    path: "log/log.log"
    encoder:
      pattern: "{d(%d/%m/%Y %H:%M:%S%.3f)} {h({l})} - {m}\n"

root:
  level: info
  appenders:
    - stdout
    - requests
